services:

  aws:
    image: localstack/localstack
    container_name: "localstack-message-orchestrator-service"
    environment:
      - SERVICES=sns
      - DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_REGION=sa-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    networks:
      - broker-localstack

  terraform:
    image: hashicorp/terraform:1.3.3
    container_name: "terraform-message-orchestrator-service"
    volumes:
      - ./infra/terraform/:/infra
    working_dir: /infra
    depends_on:
      - aws
    entrypoint: >
      sh -c "
      terraform init
      && terraform fmt
      && terraform validate
      && terraform plan -out='infra.out'
      && terraform apply infra.out"
    networks:
      - broker-localstack

  prometheus:
    container_name: "prometheus-message-orchestrator-service"
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: "kafka-message-orchestrator-service"
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: "zookeeper-message-orchestrator-service"
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: "kafdrop-message-orchestrator-service"
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  broker-kafka:
    driver: bridge
  broker-localstack:
    driver: bridge